name: arc42 PDF

on:
  push:
    branches: [main]
    paths: ["documentation/**"]
  pull_request:
    paths: ["documentation/**", ".github/workflows/arc42.yml"]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  arc42:
    uses: THD-Spatial-AI/.github/.github/workflows/arc42-pdf.yml@feat/arc42-pdf-workflow
    permissions:
      contents: write
